ci:

  autofix_prs: false

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-yaml
    args: ["--unsafe"]
  - id: check-toml
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: detect-private-key
  - id: fix-encoding-pragma
    args: ["--remove"]
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
    - id: python-check-blanket-noqa
    - id: python-check-mock-methods
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
    - id: text-unicode-replacement-char

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell
      args: ["--write-changes"]
      additional_dependencies:
        - tomli

- repo: https://github.com/ikamensh/flynt/
  rev: '1.0.1'
  hooks:
    - id: flynt

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.9.10"
  hooks:
    - id: ruff
      args: ["--fix"]

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: 1.19.1
  hooks:
    - id: blacken-docs

- repo: https://github.com/abravalheri/validate-pyproject
  rev: "v0.23"
  hooks:
    - id: validate-pyproject
