version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - graphviz
  tools:
    python: "3.12"

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
